name: Automated Testing
'on':
  push: 

jobs:
  Selenium_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: temurin
          cache: maven
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - name: Build with Maven
        run: |
          cd Magneto
          mvn -B clean test
      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: Selenium-test-reports
          if: always()
          path: Magneto/target
